DROP TABLE TNMODELVERSION ;
DROP TABLE ACTIVITYLOG ;
DROP TABLE ADDRESS ;
DROP TABLE CONTACT ;
DROP TABLE CONTACTTYPE ;
DROP TABLE BINARYTYPE ;
DROP TABLE IDTYPE ;
DROP TABLE DESTINATION ;
DROP TABLE PARTNERBINARY ;
DROP TABLE PARTNERID ;
DROP TABLE PARTNERPROFILEFIELD ;
DROP TABLE PROFILEFIELD ;
DROP TABLE REMOTE ;
DROP TABLE FIELDGROUP ;

DROP TABLE DELIVERYSERVICE ;
DROP TABLE DELIVERYJOB ;

DROP TABLE PROCESSINGRULE ;

DROP TABLE CONVERSATIONSCRIPT ;
DROP TABLE ROLEBINDING ;
DROP TABLE CONVERSATION ;

DROP TABLE BIZDOCCONTENTARCHIVE ;
DROP TABLE BIZDOCARCHIVE ;

DROP TABLE BIZDOCTYPEATTRIBUTE ;
DROP TABLE BIZDOCATTRIBUTE ;
DROP TABLE BIZDOCATTRIBUTEDEF ;
DROP TABLE BIZDOCRELATIONSHIP ;

DROP TABLE BIZDOCCONTENT ;
DROP TABLE BIZDOC ;
DROP TABLE BIZDOCTYPEDEF ;
DROP TABLE PARTNER ;
